import express from "express";
import session from "express-session";
import passport from "passport";
import {Strategy as GoogleStrategy} from "passport-google-oauth20";
import {Strategy as GitHubStrategy} from "passport-github2";
import multer from "multer";
import ffmpeg from "fluent-ffmpeg";
import dotenv from "dotenv";
import path from "path";
import fs from "fs";
import {fileURLToPath} from "url";
dotenv.config();
const __dirname=path.dirname(fileURLToPath(import.meta.url)), ROOT=path.resolve(__dirname,"..");
const app=express(), upload=multer({dest:path.join(ROOT,"uploads")});
app.use(express.json());app.use(session({secret:process.env.SESSION_SECRET||"dev-secret",resave:false,saveUninitialized:false}));
app.use(passport.initialize());app.use(passport.session());
passport.serializeUser((u,d)=>d(null,u));passport.deserializeUser((u,d)=>d(null,u));
const base=process.env.BASE_URL||"http://localhost:3000";
if(process.env.GOOGLE_CLIENT_ID) passport.use(new GoogleStrategy({clientID:process.env.GOOGLE_CLIENT_ID,clientSecret:process.env.GOOGLE_CLIENT_SECRET,callbackURL:base+"/auth/google/callback"},(_,__,p,d)=>d(null,{provider:"google",id:p.id,name:p.displayName,photo:p.photos?.[0]?.value})));
if(process.env.GITHUB_CLIENT_ID) passport.use(new GitHubStrategy({clientID:process.env.GITHUB_CLIENT_ID,clientSecret:process.env.GITHUB_CLIENT_SECRET,callbackURL:base+"/auth/github/callback"},(_,__,p,d)=>d(null,{provider:"github",id:p.id,name:p.displayName||p.username,photo:p.photos?.[0]?.value})));
app.get("/auth/google",(req,res,next)=>process.env.GOOGLE_CLIENT_ID?passport.authenticate("google",{scope:["profile","email"]})(req,res,next):res.status(503).send("Google OAuth credentials are not configured."));
app.get("/auth/google/callback",passport.authenticate("google",{failureRedirect:"/"}),(req,res)=>res.redirect("/"));
app.get("/auth/github",(req,res,next)=>process.env.GITHUB_CLIENT_ID?passport.authenticate("github",{scope:["user:email"]})(req,res,next):res.status(503).send("GitHub OAuth credentials are not configured."));
app.get("/auth/github/callback",passport.authenticate("github",{failureRedirect:"/"}),(req,res)=>res.redirect("/"));
app.get("/api/me",(req,res)=>res.json(req.user||null));app.post("/api/logout",(req,res)=>req.logout(()=>res.json({ok:true})));
app.post("/api/render",upload.single("video"),(req,res)=>{
 if(!req.file)return res.status(400).json({error:"video required"});
 const out=path.join(ROOT,"uploads",req.file.filename+"-render.mp4");
 ffmpeg(req.file.path).videoCodec("libx264").audioCodec("aac").outputOptions(["-preset fast","-movflags +faststart"]).size(req.body.resolution==="4k"?"3840x2160":"1920x1080").on("end",()=>res.download(out,"SEC-render.mp4",()=>{try{fs.unlinkSync(req.file.path);fs.unlinkSync(out)}catch{}})).on("error",e=>res.status(500).json({error:e.message})).save(out);
});
app.post("/api/ai/remove-bg",upload.single("video"),(req,res)=>res.status(501).json({error:"Connect a segmentation model (e.g. your own inference service) here. Endpoint is wired, but no model credentials/model server were supplied."}));
app.post("/api/ai/track",upload.single("video"),(req,res)=>res.status(501).json({error:"Connect an object-tracking inference service here."}));
app.post("/api/ai/captions",upload.single("video"),(req,res)=>res.status(501).json({error:"Connect a speech-to-text model/API here."}));
app.use(express.static(ROOT));app.listen(process.env.PORT||3000,()=>console.log("SEC Studio:",base));
